/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminSuccesss.java
 *
 * Created on Nov 7, 2017, 12:23:47 PM
 */
package gui;

/**
 *
 * @author yatinVM
 */
public class AdminSuccesss extends javax.swing.JFrame {

    /**
     * Creates new form AdminSuccesss
     */
    public AdminSuccesss() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbStudentRegistration = new javax.swing.JLabel();
        lbAddLiberian = new javax.swing.JLabel();
        lbViewLiberian = new javax.swing.JLabel();
        lbDeleteLiberian = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        lbDeleteStudent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName("jPanel2"); // NOI18N

        lbStudentRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/111.png"))); // NOI18N
        lbStudentRegistration.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbStudentRegistration.setName("lbStudentRegistration"); // NOI18N
        lbStudentRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbStudentRegistrationMouseClicked(evt);
            }
        });

        lbAddLiberian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        lbAddLiberian.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbAddLiberian.setName("lbAddLiberian"); // NOI18N
        lbAddLiberian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAddLiberianMouseClicked(evt);
            }
        });

        lbViewLiberian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        lbViewLiberian.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbViewLiberian.setName("lbViewLiberian"); // NOI18N
        lbViewLiberian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbViewLiberianMouseClicked(evt);
            }
        });

        lbDeleteLiberian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4.png"))); // NOI18N
        lbDeleteLiberian.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbDeleteLiberian.setName("lbDeleteLiberian"); // NOI18N
        lbDeleteLiberian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDeleteLiberianMouseClicked(evt);
            }
        });

        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5.png"))); // NOI18N
        lbLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbLogout.setName("lbLogout"); // NOI18N
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
        });

        lbDeleteStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/44.png"))); // NOI18N
        lbDeleteStudent.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbDeleteStudent.setName("lbDeleteStudent"); // NOI18N
        lbDeleteStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDeleteStudentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbViewLiberian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(128, 128, 128)
                                .addComponent(lbDeleteLiberian))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbStudentRegistration)
                                .addGap(128, 128, 128)
                                .addComponent(lbAddLiberian)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDeleteStudent)
                        .addGap(128, 128, 128)
                        .addComponent(lbLogout)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAddLiberian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbStudentRegistration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbViewLiberian)
                    .addComponent(lbDeleteLiberian, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogout)
                    .addComponent(lbDeleteStudent))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ad.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(851, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void lbStudentRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbStudentRegistrationMouseClicked
// TODO add your handling code here:
    StudentRegistrationn studReg = new StudentRegistrationn(this);
    studReg.setVisible(true);
    studReg.setSize(1100, 760);
    studReg.setLocationRelativeTo(null);
    this.dispose();
//    cameraVal = 1;
}//GEN-LAST:event_lbStudentRegistrationMouseClicked

private void lbAddLiberianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAddLiberianMouseClicked
    LibrarianRegistrationn libReg = new LibrarianRegistrationn(this);
    libReg.setVisible(true);
    libReg.setSize(1040, 960);
    libReg.setLocationRelativeTo(null);
    this.dispose();
//    cameraVal = 2;
}//GEN-LAST:event_lbAddLiberianMouseClicked

private void lbViewLiberianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbViewLiberianMouseClicked
    ViewLibrariann viewlib = new ViewLibrariann(this);
    viewlib.setVisible(true);
    viewlib.setSize(1040, 960);
    viewlib.setLocationRelativeTo(null);
    this.dispose();
}//GEN-LAST:event_lbViewLiberianMouseClicked

private void lbDeleteLiberianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDeleteLiberianMouseClicked
    DeleteLibrariann deletelib = new DeleteLibrariann(this);
    deletelib.setVisible(true);
    deletelib.setSize(1040, 960);
    deletelib.setLocationRelativeTo(null);
    this.dispose();
}//GEN-LAST:event_lbDeleteLiberianMouseClicked

private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
// TODO add your handling code here:
    LibraryMainFramee libmain = new LibraryMainFramee();
    libmain.setVisible(true);
    libmain.setLocationRelativeTo(null);
    this.dispose();
}//GEN-LAST:event_lbLogoutMouseClicked

    private void lbDeleteStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDeleteStudentMouseClicked
        // TODO add your handling code here:
        DeleteStudent deletestud = new DeleteStudent(this);
        deletestud.setVisible(true);
        deletestud.setSize(1040, 960);
        deletestud.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lbDeleteStudentMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminSuccesss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminSuccesss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminSuccesss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminSuccesss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new AdminSuccesss().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbAddLiberian;
    private javax.swing.JLabel lbDeleteLiberian;
    private javax.swing.JLabel lbDeleteStudent;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbStudentRegistration;
    private javax.swing.JLabel lbViewLiberian;
    // End of variables declaration//GEN-END:variables
}
