/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LibrarianRegistrationn.java
 *
 * Created on Nov 7, 2017, 12:31:00 PM
 */
package gui;

import dao.DB;
import dao.IssueBookDao;
import java.awt.Frame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

public class IssueBooks extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianRegistrationn
     */
    Frame frm;
//    DaoConnection dc = new DaoConnection();
    Connection conn;
    String new_trans_id = "";
    int unused_trans_id = -1;
    int id = 0;
    public static int btnView = 0;

    public IssueBooks(Frame frm) {
        initComponents();
        this.frm = frm;
//        frm.setSize(625, 520);

        conn = DB.getConnection();

        final JTextField textfield = (JTextField) cbBookName.getEditor().getEditorComponent();
        textfield.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent ke) {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        comboFilter(textfield.getText());
                    }
                });
            }
        });
//        cbBookName = new JComboBox(new Object[]{"Ester", "Jordi", "Sergi"});
//        JTextComponent editor = (JTextComponent) cbBookName.getEditor().getEditorComponent();
//        change the editor's document to our BadDocument
//        editor.setDocument(new insertString());
//        Object[] elements = new Object[]{"Cat", "Dog", "Lion", "Mouse"};      
//        AutoCompleteDecorator.decorate(cbBookName);
//        cbBookName.addItem("Cat");
//        cbBookName.addItem("dog");
//        AutoCompleteSupport.install();
    }

    public void comboFilter(String enteredText) {
        List<String> filterArray = new ArrayList<String>();
        String str1 = "";
        try {
            Connection con = DB.getConnection();
            String str = "SELECT name FROM books WHERE name LIKE '%" + enteredText + "%'";

//     Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
//      con=DriverManager.getConnection("jdbc:odbc:ds1", "sa" , "creative");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(str);
            while (rs.next()) {

                str1 = rs.getString("name");
                filterArray.add(str1);

            }
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("error" + ex);
        }

        if (filterArray.size() > 0) {
            cbBookName.setModel(new DefaultComboBoxModel(filterArray.toArray()));
            cbBookName.setSelectedItem(enteredText);
            cbBookName.showPopup();
        } else {
            cbBookName.hidePopup();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfStudentName = new javax.swing.JTextField();
        tfStuentContact = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfBookCellNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGetetails = new javax.swing.JButton();
        cbBookName = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel4.setMaximumSize(new java.awt.Dimension(464, 648));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(464, 648));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Issue Book Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SimSun", 1, 14))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Student ID :");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student Name :");
        jLabel6.setName("jLabel6"); // NOI18N

        tfStudentName.setEditable(false);
        tfStudentName.setCaretColor(new java.awt.Color(0, 102, 102));
        tfStudentName.setMinimumSize(new java.awt.Dimension(40, 24));
        tfStudentName.setName("tfStudentName"); // NOI18N
        tfStudentName.setPreferredSize(new java.awt.Dimension(280, 32));

        tfStuentContact.setEditable(false);
        tfStuentContact.setCaretColor(new java.awt.Color(0, 102, 102));
        tfStuentContact.setMinimumSize(new java.awt.Dimension(40, 24));
        tfStuentContact.setName("tfStuentContact"); // NOI18N
        tfStuentContact.setPreferredSize(new java.awt.Dimension(280, 32));
        tfStuentContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStuentContactActionPerformed(evt);
            }
        });

        jLabel2.setText("Student Contact :");
        jLabel2.setName("jLabel2"); // NOI18N

        tfID.setCaretColor(new java.awt.Color(0, 102, 102));
        tfID.setMinimumSize(new java.awt.Dimension(40, 24));
        tfID.setName("tfID"); // NOI18N
        tfID.setPreferredSize(new java.awt.Dimension(280, 32));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Book Name :");
        jLabel16.setName("jLabel16"); // NOI18N

        tfBookCellNo.setEditable(false);
        tfBookCellNo.setCaretColor(new java.awt.Color(0, 102, 102));
        tfBookCellNo.setMinimumSize(new java.awt.Dimension(40, 24));
        tfBookCellNo.setName("tfBookCellNo"); // NOI18N
        tfBookCellNo.setPreferredSize(new java.awt.Dimension(280, 32));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Book Cell No. :");
        jLabel5.setName("jLabel5"); // NOI18N

        btnGetetails.setText("Get Details");
        btnGetetails.setName("btnGetetails"); // NOI18N
        btnGetetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetetailsActionPerformed(evt);
            }
        });

        cbBookName.setEditable(true);
        cbBookName.setName("cbBookName"); // NOI18N
        cbBookName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBookNameItemStateChanged(evt);
            }
        });
        cbBookName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                cbBookNamePopupMenuCanceled(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbBookNamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBookNameActionPerformed(evt);
            }
        });
        cbBookName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbBookNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbBookNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbBookNameKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16)
                    .addComponent(jLabel5))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfBookCellNo, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(tfID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfStuentContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbBookName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGetetails, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBookName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBookCellNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnGetetails, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfStuentContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setName("jPanel10"); // NOI18N

        btnRegister.setFont(new java.awt.Font("Sylfaen 18", 1, 12)); // NOI18N
        btnRegister.setText("Issue Book");
        btnRegister.setName("btnRegister"); // NOI18N
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Sylfaen 18", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.setMaximumSize(new java.awt.Dimension(100, 25));
        btnBack.setMinimumSize(new java.awt.Dimension(110, 25));
        btnBack.setName("btnBack"); // NOI18N
        btnBack.setPreferredSize(new java.awt.Dimension(110, 25));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Book Information");

        jPanel5.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(26, 42, 57));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(861, 202));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman 14", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IssueBookTi.png"))); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel7.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    // TODO add your handling code here:

//    DaoConnection dao = new DaoConnection();
    if (("".equals(tfID.getText())) || ("".equals(tfStudentName.getText())) || ("".equals(tfBookCellNo.getText())) || ("".equals(tfStuentContact.getText()))) {
        JOptionPane.showMessageDialog(null, "Please Enter All The Fields !!!");
    } else {

//        int quantity = 0;
        String bookcallno = tfBookCellNo.getText();
        String studentid = tfID.getText();
        String studentname = tfStudentName.getText();
        String studentcontact = tfStuentContact.getText();

        if (IssueBookDao.checkBook(bookcallno)) {
            int checkQuantity = IssueBookDao.checkQuantity(studentid);
//            System.out.println("checkQuantity : "+checkQuantity);
            if (checkQuantity < 2) {

                int i = IssueBookDao.save(bookcallno, studentid, studentname, studentcontact);
                if (checkQuantity == 0) {
//                    System.out.println("checkQuantity 0 : "+checkQuantity);
                    IssueBookDao.saveQuantity(studentid, (checkQuantity + 1));
                }else{
//                    System.out.println("checkQuantity 1 : "+checkQuantity);
                    IssueBookDao.updateQuantity(studentid, (checkQuantity + 1));
                }
                if (i > 0) {
                    JOptionPane.showMessageDialog(this, "Book issued successfully!");
                    tfBookCellNo.setText("");
                    tfID.setText("");
                    tfStudentName.setText("");
                    tfStuentContact.setText("");
                    cbBookName.setSelectedItem("");
                } else {
                    JOptionPane.showMessageDialog(this, "Sorry, unable to issue!");
                }//end of save if-else
            } else {
                JOptionPane.showMessageDialog(this, "Sorry, You can't issue book!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sorry, Callno doesn't exist!");
        }//end of checkbook if-else

    }
//        }
//    }
}//GEN-LAST:event_btnRegisterActionPerformed

private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    // TODO add your handling code here:
    LibrarianSuccesss adminfrm = new LibrarianSuccesss();
    adminfrm.setSize(750, 800);
    adminfrm.setVisible(true);
    adminfrm.setLocationRelativeTo(null);
    this.dispose();
}//GEN-LAST:event_btnBackActionPerformed

    private void tfStuentContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStuentContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStuentContactActionPerformed

//    JComboBox comboBox = new JComboBox();
//    Object[] elements = new Object[]{"Cat", "Dog", "Lion", "Mouse"};
//    AutoCompleteSupport.install(comboBox, GlazedLists.eventListOf(elements));
//    boolean wordTyped(String typedWord) {
//
//        //create list for dictionary this in your case might be done via calling a method which queries db and returns results as arraylist
//        ArrayList<String> words = new ArrayList<>();
//        words.add("hello");
//        words.add("heritage");
//        words.add("happiness");
//        words.add("goodbye");
//        words.add("cruel");
//        words.add("car");
//        words.add("war");
//        words.add("will");
//        words.add("world");
//        words.add("wall");
//
//        setDictionary(words);
//        //addToDictionary("bye");//adds a single word
//
//        return super.wordTyped(typedWord);//now call super to check for any matches against newest dictionary
//    }

    private void btnGetetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetetailsActionPerformed
        // TODO add your handling code here:
        String text = tfID.getText();
        if (!text.equals("")) {
//            Pattern pattern4 = Pattern.compile("^[a-zA-Z0-9]*$");
//            Matcher matcherQuantity = pattern4.matcher(text);
//            if (!matcherQuantity.matches()) {
//                JOptionPane.showMessageDialog(null, "Enter correct ID !");
//            } else {
            ArrayList checkStudent = IssueBookDao.checkStudent(text);
            if (checkStudent.size() > 0) {
                tfStudentName.setText(checkStudent.get(0).toString());
                tfStuentContact.setText(checkStudent.get(1).toString());
            } else {
                JOptionPane.showMessageDialog(null, "No record found !");
                tfStudentName.setText("");
                tfStuentContact.setText("");
            }
//            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter Student ID !");
        }
    }//GEN-LAST:event_btnGetetailsActionPerformed

    private void cbBookNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbBookNameKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_cbBookNameKeyReleased

    private void cbBookNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbBookNameKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_cbBookNameKeyTyped

    private void cbBookNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbBookNameKeyPressed

    }//GEN-LAST:event_cbBookNameKeyPressed

    private void cbBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBookNameActionPerformed

    }//GEN-LAST:event_cbBookNameActionPerformed

    private void cbBookNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBookNameItemStateChanged

    }//GEN-LAST:event_cbBookNameItemStateChanged

    private void cbBookNamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbBookNamePopupMenuWillBecomeInvisible
        String cell = IssueBookDao.getCell(cbBookName.getEditor().getItem().toString());
        tfBookCellNo.setText(cell);
    }//GEN-LAST:event_cbBookNamePopupMenuWillBecomeInvisible

    private void cbBookNamePopupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbBookNamePopupMenuCanceled
        // TODO add your handling code here:

    }//GEN-LAST:event_cbBookNamePopupMenuCanceled

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new LibrarianRegistrationn().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGetetails;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox cbBookName;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JTextField tfBookCellNo;
    public javax.swing.JTextField tfID;
    public javax.swing.JTextField tfStudentName;
    public javax.swing.JTextField tfStuentContact;
    // End of variables declaration//GEN-END:variables
}
