/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LibrarianRegistrationn.java
 *
 * Created on Nov 7, 2017, 12:31:00 PM
 */
package gui;

//import daoo.DaoConnection;
import dao.DB;
import java.awt.Frame;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
//import liverecognition.LiveRecognitionApp;
//import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;

/**
 *
 * @author yatinVM
 */
public class LibrarianRegistrationn extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianRegistrationn
     */
    Frame frm;
//    DaoConnection dc = new DaoConnection();
    Connection conn;
    String new_trans_id = "";
    int unused_trans_id = -1;
//    int id = 0;
    public static int btnView = 0;

    public LibrarianRegistrationn(Frame frm) {
        initComponents();
        this.frm = frm;

        conn = DB.getConnection();
//        MainPln.setView = 0;

        Vector trans_ids = new Vector();

        String sql = "select id from librarian";
//        String sql = "select id from registrationtbl";
        try {
            PreparedStatement pre = conn.prepareStatement(sql);
            ResultSet rs = pre.executeQuery(sql);

            while (rs.next()) {
                trans_ids.add(rs.getString("id"));
            }

            if (!trans_ids.isEmpty()) {
                for (int i = 1; i <= trans_ids.size(); i++) {
                    if (!trans_ids.elementAt(i - 1).toString().endsWith(String.valueOf(i))) {
                        unused_trans_id = i;
                        break;
                    }
                }
            }

            if (unused_trans_id == -1) {
                unused_trans_id = trans_ids.size() + 1;
            }

            if (unused_trans_id <= 9) {
                new_trans_id = "LIB0000" + unused_trans_id;
            } else if (unused_trans_id <= 99) {
                new_trans_id = "LIB000" + unused_trans_id;
            } else if (unused_trans_id <= 999) {
                new_trans_id = "LIB00" + unused_trans_id;
            } else if (unused_trans_id <= 9999) {
                new_trans_id = "LIB0" + unused_trans_id;
            } else if (unused_trans_id <= 99999) {
                new_trans_id = "LIB" + unused_trans_id;
            }
        } catch (Exception e) {
            System.out.println("Exception : " + e);
        }
        tfSID.setText(new_trans_id + "");
//        try {
//            PreparedStatement pre = conn.prepareStatement(sql);
//            ResultSet rs = pre.executeQuery(sql);
//
//            while (rs.next()) {
//                id = rs.getInt("id");
//            }
//
//            if (id != 0) {
//                id = id + 1;
//            } else {
//                id = 1;
//            }
//            System.out.println("unused_trans_id : " + id);

//            if (unused_trans_id <= 9) {
//                new_trans_id = "EMP0000" + unused_trans_id;
//            } else if (unused_trans_id <= 99) {
//                new_trans_id = "EMP000" + unused_trans_id;
//            } else if (unused_trans_id <= 999) {
//                new_trans_id = "EMP00" + unused_trans_id;
//            } else if (unused_trans_id <= 9999) {
//                new_trans_id = "EMP0" + unused_trans_id;
//            } else if (unused_trans_id <= 99999) {
//                new_trans_id = "EMP" + unused_trans_id;
//            }
//        } catch (Exception e) {
//            System.out.println("Exception : " + e);
//        }
        tfSID.setText(new_trans_id + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfSID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfcontact = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox();
        tfPassword = new javax.swing.JPasswordField();
        jPanel10 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel4.setMaximumSize(new java.awt.Dimension(464, 648));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(464, 648));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SimSun", 1, 14))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        taAddress.setColumns(20);
        taAddress.setRows(5);
        taAddress.setName("taAddress"); // NOI18N
        jScrollPane2.setViewportView(taAddress);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Address :");
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender :");
        jLabel8.setName("jLabel8"); // NOI18N

        tfSID.setEditable(false);
        tfSID.setMinimumSize(new java.awt.Dimension(40, 24));
        tfSID.setName("tfSID"); // NOI18N
        tfSID.setPreferredSize(new java.awt.Dimension(280, 32));

        jLabel18.setText("ID : ");
        jLabel18.setName("jLabel18"); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name :");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile No. :");
        jLabel6.setName("jLabel6"); // NOI18N

        tfcontact.setCaretColor(new java.awt.Color(0, 102, 102));
        tfcontact.setMinimumSize(new java.awt.Dimension(40, 24));
        tfcontact.setName("tfcontact"); // NOI18N
        tfcontact.setPreferredSize(new java.awt.Dimension(280, 32));

        tfEmail.setCaretColor(new java.awt.Color(0, 102, 102));
        tfEmail.setMinimumSize(new java.awt.Dimension(40, 24));
        tfEmail.setName("tfEmail"); // NOI18N
        tfEmail.setPreferredSize(new java.awt.Dimension(280, 32));

        jLabel2.setText("Email ID :");
        jLabel2.setName("jLabel2"); // NOI18N

        tfName.setCaretColor(new java.awt.Color(0, 102, 102));
        tfName.setMinimumSize(new java.awt.Dimension(40, 24));
        tfName.setName("tfName"); // NOI18N
        tfName.setPreferredSize(new java.awt.Dimension(280, 32));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Password :");
        jLabel16.setName("jLabel16"); // NOI18N

        cbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cbGender.setName("cbGender"); // NOI18N

        tfPassword.setName("tfPassword"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(tfcontact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbGender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setName("jPanel10"); // NOI18N

        btnRegister.setFont(new java.awt.Font("Sylfaen 18", 1, 12)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.setName("btnRegister"); // NOI18N
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Sylfaen 18", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setMaximumSize(new java.awt.Dimension(110, 25));
        btnReset.setMinimumSize(new java.awt.Dimension(110, 25));
        btnReset.setName("btnReset"); // NOI18N
        btnReset.setPreferredSize(new java.awt.Dimension(110, 25));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Sylfaen 18", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.setMaximumSize(new java.awt.Dimension(100, 25));
        btnBack.setMinimumSize(new java.awt.Dimension(110, 25));
        btnBack.setName("btnBack"); // NOI18N
        btnBack.setPreferredSize(new java.awt.Dimension(110, 25));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(26, 42, 57));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(861, 202));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman 14", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lib1.png"))); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel7.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    // TODO add your handling code here:
    Connection conn = null;
//    DaoConnection dao = new DaoConnection();

    if (("".equals(tfName.getText())) || ("".equals(tfcontact.getText())) || ("".equals(taAddress.getText())) || ("".equals(tfEmail.getText())) || ("".equals(tfPassword.getText()))) {
        JOptionPane.showMessageDialog(null, "Please Enter All The Fields !!!");
    } else {
        String emailregex = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
        Boolean checkEmail = tfEmail.getText().trim().matches(emailregex);

        Pattern pattern = Pattern.compile("\\d{10}");
        Matcher matcherMobile = pattern.matcher(tfcontact.getText());
//            Matcher matcherEnroll = pattern.matcher(txtEID.getText());

        Pattern pattern1 = Pattern.compile("^[a-zA-Z]+([\\s][a-zA-Z]+)*$");
        Matcher matcherFName = pattern1.matcher(tfName.getText().trim());

        Pattern patternLast = Pattern.compile("^[a-zA-Z]+([\\s][a-zA-Z]+)*$");
        Matcher matcherLast = patternLast.matcher(tfPassword.getText().trim());

        if (!matcherMobile.matches()) {
            JOptionPane.showMessageDialog(null, "Enter Valid Mobile Nuumber !!!");
        } else if (!matcherFName.matches()) {
            JOptionPane.showMessageDialog(null, "Enter Valid Name !!!");
        } else if (!matcherLast.matches()) {
            JOptionPane.showMessageDialog(null, "Enter Valid City !!!");
        } else if (!checkEmail) {
            JOptionPane.showMessageDialog(null, "Enter Valid Email ID !!!");
        } else {

            FileInputStream input = null;
            try {
                int x = 0;
                String empid = tfSID.getText();
                String name = tfName.getText();
                String pass = tfPassword.getText();
                String contact = tfcontact.getText();
                String email = tfEmail.getText();
                String address = taAddress.getText();
                String gender = cbGender.getSelectedItem().toString();
//                String s8 = System.getProperty("user.dir") + File.separator + "images" + File.separator + "temp.jpg";
//                input = new FileInputStream(s8);

                System.out.println(empid);
                System.out.println(contact);
                System.out.println(email);
                System.out.println(address);

                try {
                    conn = DB.getConnection();
                    PreparedStatement ps;
                    ps = conn.prepareStatement("insert into librarian (id,name,email,address,password,contact,gender)" + (" values(?,?,?,?,?,?,?)"));

                    ps.setString(1, new_trans_id);
                    ps.setString(2, name);
                    ps.setString(3, email);
                    ps.setString(4, address);
                    ps.setString(5, pass);
                    ps.setString(6, contact);
                    ps.setString(7, gender);
//                    ps.setBlob(8, input);

                    ps.executeUpdate();
                    conn.close();
                    x++;
                    if (x > 0) {
                        JOptionPane.showMessageDialog(null, "Librarian Registration Successful !!!");
                        taAddress.setFocusable(false);
                        tfcontact.setText("");
                        tfName.setText("");
                        tfSID.setText("");
                        tfEmail.setText("");
                        tfPassword.setText("");
//                        tfGender.setText("");
                        taAddress.setText("");
//                        this.pnlPhotoLib.removeAll();
//                        this.pnlPhotoLib.updateUI();
                        tfSID.setRequestFocusEnabled(true);
                        tfSID.setFocusable(true);
                        taAddress.setFocusable(true);
                        tfcontact.setFocusable(true);
//                        tfSID.setText((id + 1) + "");
                        AdminSuccesss adminfrm = new AdminSuccesss();
                        adminfrm.setSize(750, 800);
                        adminfrm.setVisible(true);
                        adminfrm.setLocationRelativeTo(null);
                        this.dispose();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            } finally {
            }
        }
    }
}//GEN-LAST:event_btnRegisterActionPerformed

private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

    taAddress.setFocusable(false);
    tfcontact.setText("");
    tfName.setText("");
    tfPassword.setText("");
    tfEmail.setText("");
    taAddress.setText("");
//    tfGender.setText("");

//    this.pnlPhotoLib.removeAll();
//    this.pnlPhotoLib.updateUI();
    tfSID.setRequestFocusEnabled(true);
    tfSID.setFocusable(true);
    taAddress.setFocusable(true);
    tfcontact.setFocusable(true);
    JOptionPane.showMessageDialog(null, "Fields Cleared !!!");
}//GEN-LAST:event_btnResetActionPerformed

private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    // TODO add your handling code here:
    AdminSuccesss adminfrm = new AdminSuccesss();
    adminfrm.setSize(750, 800);
    adminfrm.setVisible(true);
    adminfrm.setLocationRelativeTo(null);
    this.dispose();
}//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new LibrarianRegistrationn().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cbGender;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taAddress;
    public javax.swing.JTextField tfEmail;
    public javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfSID;
    public javax.swing.JTextField tfcontact;
    // End of variables declaration//GEN-END:variables
}
