/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminSuccesss.java
 *
 * Created on Nov 7, 2017, 12:23:47 PM
 */
package gui;

/**
 *
 * @author yatinVM
 */
public class LibrarianSuccesss extends javax.swing.JFrame {

    /**
     * Creates new form AdminSuccesss
     */
    public LibrarianSuccesss() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbAddBooks = new javax.swing.JLabel();
        lbViewBooks = new javax.swing.JLabel();
        lbIssueBook = new javax.swing.JLabel();
        lbViewIssue = new javax.swing.JLabel();
        lbReturnBook = new javax.swing.JLabel();
        lbViewStudents = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName("jPanel2"); // NOI18N

        lbAddBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AddBook.png"))); // NOI18N
        lbAddBooks.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbAddBooks.setName("lbAddBooks"); // NOI18N
        lbAddBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAddBooksMouseClicked(evt);
            }
        });

        lbViewBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/viewBooks.png"))); // NOI18N
        lbViewBooks.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbViewBooks.setName("lbViewBooks"); // NOI18N
        lbViewBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbViewBooksMouseClicked(evt);
            }
        });

        lbIssueBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Issued.png"))); // NOI18N
        lbIssueBook.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbIssueBook.setName("lbIssueBook"); // NOI18N
        lbIssueBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIssueBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbIssueBookMouseEntered(evt);
            }
        });

        lbViewIssue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ViewIssued.png"))); // NOI18N
        lbViewIssue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbViewIssue.setName("lbViewIssue"); // NOI18N
        lbViewIssue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbViewIssueMouseClicked(evt);
            }
        });

        lbReturnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ReturnBook.png"))); // NOI18N
        lbReturnBook.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbReturnBook.setName("lbReturnBook"); // NOI18N
        lbReturnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReturnBookMouseClicked(evt);
            }
        });

        lbViewStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/viewStudentsL.png"))); // NOI18N
        lbViewStudents.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbViewStudents.setName("lbViewStudents"); // NOI18N
        lbViewStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbViewStudentsMouseClicked(evt);
            }
        });

        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logOutt.jpg"))); // NOI18N
        lbLogout.setName("lbLogout"); // NOI18N
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbReturnBook)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbIssueBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbAddBooks)))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbViewBooks)
                            .addComponent(lbViewIssue)
                            .addComponent(lbViewStudents)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lbLogout)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbViewBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAddBooks))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbViewIssue)
                    .addComponent(lbIssueBook))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbReturnBook)
                    .addComponent(lbViewStudents))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbLogout)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libH.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(711, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 129, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void lbAddBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAddBooksMouseClicked
// TODO add your handling code here:
    AddBook add = new AddBook(this);
    add.setVisible(true);
    add.setSize(720, 610);
    add.setLocationRelativeTo(null);
    this.dispose();
//    cameraVal = 1;
}//GEN-LAST:event_lbAddBooksMouseClicked

private void lbViewBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbViewBooksMouseClicked
    ViewBooks libReg = new ViewBooks(this);
    libReg.setVisible(true);
    libReg.setSize(1040, 960);
    libReg.setLocationRelativeTo(null);
    this.dispose();
//    cameraVal = 2;
}//GEN-LAST:event_lbViewBooksMouseClicked

private void lbIssueBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIssueBookMouseClicked
    IssueBooks add = new IssueBooks(this);
    add.setVisible(true);
    add.setSize(720, 610);
    add.setLocationRelativeTo(null);
    this.dispose();
}//GEN-LAST:event_lbIssueBookMouseClicked

private void lbViewIssueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbViewIssueMouseClicked
    ViewIssuedBooks viewIssue = new ViewIssuedBooks(this);
    viewIssue.setVisible(true);
    viewIssue.setSize(1040, 960);
    viewIssue.setLocationRelativeTo(null);
    this.dispose();
}//GEN-LAST:event_lbViewIssueMouseClicked

private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
// TODO add your handling code here:
    LibraryMainFramee libmain = new LibraryMainFramee();
    libmain.setVisible(true);
    libmain.setLocationRelativeTo(null);
    this.dispose();
}//GEN-LAST:event_lbLogoutMouseClicked

    private void lbReturnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReturnBookMouseClicked
        // TODO add your handling code here:
        ReturnBooks add = new ReturnBooks(this);
        add.setVisible(true);
        add.setSize(720, 610);
        add.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lbReturnBookMouseClicked

    private void lbViewStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbViewStudentsMouseClicked
        // TODO add your handling code here:
        ViewStudents add = new ViewStudents(this);
        add.setVisible(true);
        add.setSize(1040, 960);
        add.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lbViewStudentsMouseClicked

    private void lbIssueBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIssueBookMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbIssueBookMouseEntered

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminSuccesss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminSuccesss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminSuccesss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminSuccesss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new AdminSuccesss().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbAddBooks;
    private javax.swing.JLabel lbIssueBook;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbReturnBook;
    private javax.swing.JLabel lbViewBooks;
    private javax.swing.JLabel lbViewIssue;
    private javax.swing.JLabel lbViewStudents;
    // End of variables declaration//GEN-END:variables
}
