/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentRegistrationn.java
 *
 * Created on Nov 7, 2017, 3:36:50 PM
 */
package gui;

//import daoo.DaoConnection;
import dao.DB;
import java.awt.Frame;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author yatinVM
 */
public class StudentRegistrationn extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegistrationn
     */
    Frame frm;
//    DaoConnection dc = new DaoConnection();
    Connection conn;
    String new_trans_id = "";
    int unused_trans_id = -1;
//    int id = 0;

    public StudentRegistrationn(Frame frm) {
        initComponents();
        this.frm = frm;

        conn = DB.getConnection();
//        MainPln.setView = 0;

        Vector trans_ids = new Vector();

//        String sql = "select id from registrationtbl";
//        try {
//            PreparedStatement pre = conn.prepareStatement(sql);
//            ResultSet rs = pre.executeQuery(sql);
//            while (rs.next()) {
//                id = rs.getInt("id");
//            }
//
//            if (id != 0) {
//                id = id + 1;
//            } else {
//                id = 1;
//            }
//            System.out.println("unused_trans_id : " + id);
        String sql = "select id from registrationtbl";
        try {
            PreparedStatement pre = conn.prepareStatement(sql);
            ResultSet rs = pre.executeQuery(sql);

            while (rs.next()) {
                trans_ids.add(rs.getString("id"));
            }

            if (!trans_ids.isEmpty()) {
                for (int i = 1; i <= trans_ids.size(); i++) {
                    if (!trans_ids.elementAt(i - 1).toString().endsWith(String.valueOf(i))) {
                        unused_trans_id = i;
                        break;
                    }
                }
            }

            if (unused_trans_id == -1) {
                unused_trans_id = trans_ids.size() + 1;
            }

            if (unused_trans_id <= 9) {
                new_trans_id = "ST0000" + unused_trans_id;
            } else if (unused_trans_id <= 99) {
                new_trans_id = "ST000" + unused_trans_id;
            } else if (unused_trans_id <= 999) {
                new_trans_id = "ST00" + unused_trans_id;
            } else if (unused_trans_id <= 9999) {
                new_trans_id = "ST0" + unused_trans_id;
            } else if (unused_trans_id <= 99999) {
                new_trans_id = "ST" + unused_trans_id;
            }
        } catch (Exception e) {
            System.out.println("Exception : " + e);
        }
        tfSID.setText(new_trans_id + "");

//            if (unused_trans_id <= 9) {
//                new_trans_id = "EMP0000" + unused_trans_id;
//            } else if (unused_trans_id <= 99) {
//                new_trans_id = "EMP000" + unused_trans_id;
//            } else if (unused_trans_id <= 999) {
//                new_trans_id = "EMP00" + unused_trans_id;
//            } else if (unused_trans_id <= 9999) {
//                new_trans_id = "EMP0" + unused_trans_id;
//            } else if (unused_trans_id <= 99999) {
//                new_trans_id = "EMP" + unused_trans_id;
//            }
//        } catch (Exception e) {
//            System.out.println("Exception : " + e);
//        }
//        tfSID.setText(id + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jcBloodgroup = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jXDatePickerDOB = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        tfSID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfcontact = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfLast = new javax.swing.JTextField();
        tfname = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbPOY = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfReason = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbHE = new javax.swing.JComboBox();
        tfNameofSchool = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAddressofSchool = new javax.swing.JTextArea();
        tfCity = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel4.setMaximumSize(new java.awt.Dimension(464, 648));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(464, 648));

        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Information"));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        taAddress.setColumns(20);
        taAddress.setRows(5);
        taAddress.setName("taAddress"); // NOI18N
        jScrollPane2.setViewportView(taAddress);

        jLabel15.setText("Address :");
        jLabel15.setName("jLabel15"); // NOI18N

        jcBloodgroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        jcBloodgroup.setMaximumSize(new java.awt.Dimension(56, 18));
        jcBloodgroup.setMinimumSize(new java.awt.Dimension(56, 18));
        jcBloodgroup.setName("jcBloodgroup"); // NOI18N
        jcBloodgroup.setPreferredSize(new java.awt.Dimension(56, 18));

        jLabel12.setText("Blood Group  :");
        jLabel12.setName("jLabel12"); // NOI18N

        jXDatePickerDOB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jXDatePickerDOB.setMinimumSize(new java.awt.Dimension(140, 26));
        jXDatePickerDOB.setName("jXDatePickerDOB"); // NOI18N
        jXDatePickerDOB.setPreferredSize(new java.awt.Dimension(140, 26));

        jLabel1.setText("Gender :");
        jLabel1.setName("jLabel1"); // NOI18N

        tfSID.setEditable(false);
        tfSID.setMinimumSize(new java.awt.Dimension(40, 24));
        tfSID.setName("tfSID"); // NOI18N
        tfSID.setPreferredSize(new java.awt.Dimension(280, 32));
        tfSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSIDActionPerformed(evt);
            }
        });

        jLabel18.setText("ID :");
        jLabel18.setName("jLabel18"); // NOI18N

        jLabel4.setText("First Name :");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel9.setText("Last Name :");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel6.setText("Mobile No. :");
        jLabel6.setName("jLabel6"); // NOI18N

        tfcontact.setMinimumSize(new java.awt.Dimension(40, 24));
        tfcontact.setName("tfcontact"); // NOI18N
        tfcontact.setPreferredSize(new java.awt.Dimension(280, 32));

        tfEmail.setMinimumSize(new java.awt.Dimension(40, 24));
        tfEmail.setName("tfEmail"); // NOI18N
        tfEmail.setPreferredSize(new java.awt.Dimension(280, 32));

        jLabel2.setText("Email ID :");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel17.setText("DOB :");
        jLabel17.setName("jLabel17"); // NOI18N

        tfLast.setMinimumSize(new java.awt.Dimension(40, 24));
        tfLast.setName("tfLast"); // NOI18N
        tfLast.setPreferredSize(new java.awt.Dimension(280, 32));

        tfname.setMinimumSize(new java.awt.Dimension(40, 24));
        tfname.setName("tfname"); // NOI18N
        tfname.setPreferredSize(new java.awt.Dimension(280, 32));

        cbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cbGender.setName("cbGender"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfLast, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jXDatePickerDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tfcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jcBloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfSID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcBloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePickerDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel1)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setName("jPanel10"); // NOI18N

        btnRegister.setText("Registeration");
        btnRegister.setName("btnRegister"); // NOI18N
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.setMaximumSize(new java.awt.Dimension(110, 25));
        btnReset.setMinimumSize(new java.awt.Dimension(110, 25));
        btnReset.setName("btnReset"); // NOI18N
        btnReset.setPreferredSize(new java.awt.Dimension(110, 25));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.setMaximumSize(new java.awt.Dimension(100, 25));
        btnBack.setMinimumSize(new java.awt.Dimension(110, 25));
        btnBack.setName("btnBack"); // NOI18N
        btnBack.setPreferredSize(new java.awt.Dimension(110, 25));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Eductional Details"));
        jPanel6.setName("jPanel6"); // NOI18N

        jLabel11.setText("City :");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel10.setText("School Name :");
        jLabel10.setName("jLabel10"); // NOI18N

        cbPOY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        cbPOY.setMinimumSize(new java.awt.Dimension(62, 24));
        cbPOY.setName("cbPOY"); // NOI18N
        cbPOY.setPreferredSize(new java.awt.Dimension(62, 26));

        jLabel14.setText("Reason to Leave School :");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel16.setText("School Address :");
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel19.setText("Passout Year :");
        jLabel19.setName("jLabel19"); // NOI18N

        tfReason.setMinimumSize(new java.awt.Dimension(40, 24));
        tfReason.setName("tfReason"); // NOI18N
        tfReason.setPreferredSize(new java.awt.Dimension(280, 32));

        jLabel13.setText("Higher Eduction : ");
        jLabel13.setName("jLabel13"); // NOI18N

        cbHE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "SSC", "HSC", "BE", "ME", "MBA", "Bsc", "BCS", "Msc", "Phd" }));
        cbHE.setMinimumSize(new java.awt.Dimension(62, 24));
        cbHE.setName("cbHE"); // NOI18N
        cbHE.setPreferredSize(new java.awt.Dimension(62, 32));

        tfNameofSchool.setName("tfNameofSchool"); // NOI18N
        tfNameofSchool.setPreferredSize(new java.awt.Dimension(6, 26));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        taAddressofSchool.setColumns(20);
        taAddressofSchool.setRows(5);
        taAddressofSchool.setName("taAddressofSchool"); // NOI18N
        jScrollPane1.setViewportView(taAddressofSchool);

        tfCity.setName("tfCity"); // NOI18N
        tfCity.setPreferredSize(new java.awt.Dimension(6, 26));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPOY, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(tfNameofSchool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(tfReason, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbHE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNameofSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbHE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPOY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfReason, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(861, 202));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Onl.png"))); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel7.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    // TODO add your handling code here:
    Connection conn = null;
//    DaoConnection dao = new DaoConnection();

    if (("".equals(tfname.getText())) || ("".equals(tfcontact.getText())) || ("".equals(taAddress.getText())) || ("".equals(tfLast.getText())) || ("".equals(tfEmail.getText())) || ("".equals(tfReason.getText())) || ("".equals(tfLast.getText()))) {
        JOptionPane.showMessageDialog(null, "Please Enter All The Fields !!!");
    } else {
        String emailregex = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
        Boolean checkEmail = tfEmail.getText().trim().matches(emailregex);

        Pattern pattern = Pattern.compile("\\d{10}");
        Matcher matcherMobile = pattern.matcher(tfcontact.getText());
//            Matcher matcherEnroll = pattern.matcher(txtEID.getText());

        Pattern pattern1 = Pattern.compile("^[a-zA-Z]+([\\s][a-zA-Z]+)*$");
        Matcher matcherFName = pattern1.matcher(tfname.getText().trim());

        Pattern patternLast = Pattern.compile("^[a-zA-Z]+([\\s][a-zA-Z]+)*$");
        Matcher matcherLast = patternLast.matcher(tfLast.getText().trim());

        if (!matcherMobile.matches()) {
            JOptionPane.showMessageDialog(null, "Enter Valid Mobile Nuumber !!!");
        } else if (!matcherFName.matches()) {
            JOptionPane.showMessageDialog(null, "Enter Valid First Name !!!");
        } else if (!matcherLast.matches()) {
            JOptionPane.showMessageDialog(null, "Enter Valid Last Name !!!");
        } else if (!checkEmail) {
            JOptionPane.showMessageDialog(null, "Enter Valid Email ID !!!");
        } else {

            FileInputStream input = null;
            try {
                int x = 0;
                String empid = tfSID.getText();
                String fname = tfname.getText();
                String lname = tfLast.getText();
                String contact = tfcontact.getText();
                String email = tfEmail.getText();
                Date dob = jXDatePickerDOB.getDate();
                String bg = (String) jcBloodgroup.getSelectedItem();
                String address = taAddress.getText();
                String gender = cbGender.getSelectedItem().toString();
                String schoolName = tfNameofSchool.getText();
                String schoolAddress = taAddressofSchool.getText();
                String city = tfCity.getText();
                String poy = (String) cbPOY.getSelectedItem();
                String reason = tfReason.getText();
                String hedu = (String) cbHE.getSelectedItem();
//                String s8 = System.getProperty("user.dir") + File.separator + "images" + File.separator + "temp.jpg";
//                input = new FileInputStream(s8);

//                String status = tfGender.getText();
                SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");
                String dtdob = dt.format(dob);

                System.out.println(empid);
                System.out.println(fname);
                System.out.println(lname);
                System.out.println(contact);
                System.out.println(email);
                System.out.println(dtdob);
                System.out.println(bg);
                System.out.println(address);
                System.out.println(poy);

                try {
                    conn = DB.getConnection();
                    PreparedStatement ps;
                    ps = conn.prepareStatement("insert into registrationtbl (id,fname,lname,contact,email,dob,bg,address,gender,nameofschool,addressofschool,city,passoutyear,reason,edu)" + (" values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"));

                    ps.setString(1, new_trans_id);
                    ps.setString(2, fname);
                    ps.setString(3, lname);
                    ps.setString(4, contact);
                    ps.setString(5, email);
                    ps.setString(6, dtdob);
                    ps.setString(7, bg);
                    ps.setString(8, address);
                    ps.setString(9, gender);
                    ps.setString(10, schoolName);
                    ps.setString(11, schoolAddress);
                    ps.setString(12, city);
                    ps.setString(13, poy);
                    ps.setString(14, reason);
                    ps.setString(15, hedu);
//                    ps.setBlob(16, input);

                    ps.executeUpdate();
                    conn.close();
                    x++;
                    if (x > 0) {

                        JOptionPane.showMessageDialog(null, "Student Registration Successful !!!");
                        taAddress.setFocusable(false);
                        tfcontact.setText("");
                        tfLast.setText("");
                        tfname.setText("");
                        tfSID.setText("");
                        tfEmail.setText("");
                        cbHE.setSelectedIndex(0);
                        jcBloodgroup.setSelectedIndex(0);
                        tfNameofSchool.setText("");
                        tfCity.setText("");
                        taAddressofSchool.setText("");
                        cbPOY.setSelectedIndex(0);
                        tfReason.setText("");
                        cbHE.setSelectedIndex(0);
                        taAddress.setText("");
//                        tfGender.setText("");
                        jXDatePickerDOB.setDate(null);
                        this.jXDatePickerDOB.updateUI();
                        tfSID.setRequestFocusEnabled(true);
                        tfSID.setFocusable(true);
                        taAddress.setFocusable(true);
                        tfcontact.setFocusable(true);
                        AdminSuccesss adminfrm = new AdminSuccesss();
                        adminfrm.setSize(750, 800);
                        adminfrm.setVisible(true);
                        adminfrm.setLocationRelativeTo(null);
                        this.dispose();
//                        tfSID.setText((new_trans_id + 1) + "");

                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            } finally {
            }
        }
    }
}//GEN-LAST:event_btnRegisterActionPerformed

private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    // TODO add your handling code here:
    taAddress.setFocusable(false);
    tfcontact.setText("");
    tfLast.setText("");
    tfname.setText("");
    tfNameofSchool.setText("");
    tfCity.setText("");
    taAddressofSchool.setText("");
    tfEmail.setText("");
    cbHE.setSelectedIndex(0);
    jcBloodgroup.setSelectedIndex(0);
    cbPOY.setSelectedIndex(0);
    tfReason.setText("");
    cbHE.setSelectedIndex(0);
    taAddress.setText("");
//    tfGender.setText("");
    jXDatePickerDOB.setDate(null);
    this.jXDatePickerDOB.updateUI();
    tfSID.setRequestFocusEnabled(true);
    tfSID.setFocusable(true);
    taAddress.setFocusable(true);
    tfcontact.setFocusable(true);
    JOptionPane.showMessageDialog(null, "Fields Cleared !!!");
}//GEN-LAST:event_btnResetActionPerformed

private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    // TODO add your handling code here:

    AdminSuccesss adminfrm = new AdminSuccesss();
    adminfrm.setSize(750, 800);
    adminfrm.setVisible(true);
    adminfrm.setLocationRelativeTo(null);
    this.dispose();
//    MainPln.PnelMn.removeAll();
//    //                            gui.MainPanel.add(new Student_Registration(gui));
//    MainPln.PnelMn.add(new Login(frm));
//    MainPln.PnelMn.updateUI();
}//GEN-LAST:event_btnBackActionPerformed

    private void tfSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSIDActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentRegistrationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new StudentRegistrationn().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cbGender;
    private javax.swing.JComboBox cbHE;
    private javax.swing.JComboBox cbPOY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public org.jdesktop.swingx.JXDatePicker jXDatePickerDOB;
    private javax.swing.JComboBox jcBloodgroup;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTextArea taAddressofSchool;
    private javax.swing.JTextField tfCity;
    public javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfLast;
    private javax.swing.JTextField tfNameofSchool;
    public javax.swing.JTextField tfReason;
    private javax.swing.JTextField tfSID;
    public javax.swing.JTextField tfcontact;
    public javax.swing.JTextField tfname;
    // End of variables declaration//GEN-END:variables
}
